spring:
  config:
    import: optional:file:.env[.properties]   # ← lleer el archivo .env.properties si existe, pero no lanzar error si no existe
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 30000
      connection-test-query: select 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true